#!/usr/bin/env bash
#Install nginx web serverConfigure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
echo "301 Moved Permanently" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.xxcf.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
