#!/usr/bin/env bash
#configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Alx" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/^\slocation.*/i \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
echo "welcome" | sudo tee /var/www/html/custom_404.html
sudo service nginx start