#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i '$ a\ \nfrontend\n\t bind *:80\n\tmode http\n\tdefault_backend\n\nbackend\n\tbalance roundrobin\n\tserver 1034-web-01 18.235.233.229:80 check\n\tserver 1034-web-02 54.236.47.100:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
