#!/usr/bin/env bash
# Configures an Ubuntu server
# from localhost 127.0.0.1 and facebook.com resolves to 157.240.11.35
# to localhost 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts